using System.Collections.Immutable;
using System.ComponentModel;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

// Polyfill so positional records can be used on netstandard2.0 (no System.Runtime.CompilerServices.IsExternalInit).
namespace System.Runtime.CompilerServices
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static class IsExternalInit { }
}

namespace XamlLint.Core.SourceGen
{
    [Generator(LanguageNames.CSharp)]
    public sealed class RuleCatalogGenerator : IIncrementalGenerator
    {
        private const string AttributeFullName = "XamlLint.Core.XamlRuleAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var rules = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFullName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => Extract(ctx))
                .Where(static r => r is not null)
                .Select(static (r, _) => r!);

            var collected = rules.Collect();

            context.RegisterSourceOutput(collected, static (spc, rs) =>
            {
                var list = rs.ToImmutableArray();
                EmitMetadataProperties(spc, list);
                EmitCatalog(spc, list);
            });
        }

        private static RuleInfo? Extract(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not INamedTypeSymbol sym) return null;
            if (ctx.Attributes.Length == 0) return null;
            var attr = ctx.Attributes[0];

            string? GetString(string name) =>
                attr.NamedArguments.FirstOrDefault(p => p.Key == name).Value.Value as string;
            int? GetEnumInt(string name)
            {
                var v = attr.NamedArguments.FirstOrDefault(p => p.Key == name).Value.Value;
                return v is int i ? i : null;
            }
            bool GetBool(string name) =>
                attr.NamedArguments.FirstOrDefault(p => p.Key == name).Value.Value is true;

            var id = GetString("Id");
            var title = GetString("Title");
            var helpUri = GetString("HelpUri");
            var upstream = GetString("UpstreamId");
            var replacedBy = GetString("ReplacedBy");
            var deprecated = GetBool("Deprecated");
            var severity = GetEnumInt("DefaultSeverity");
            var dialects = GetEnumInt("Dialects");

            if (id is null || title is null || helpUri is null || severity is null || dialects is null)
                return null;

            return new RuleInfo(
                FullyQualifiedTypeName: sym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                SimpleTypeName: sym.Name,
                Namespace: sym.ContainingNamespace.ToDisplayString(),
                Id: id,
                UpstreamId: upstream,
                Title: title,
                DefaultSeverity: severity.Value,
                Dialects: dialects.Value,
                HelpUri: helpUri,
                Deprecated: deprecated,
                ReplacedBy: replacedBy);
        }

        private static void EmitMetadataProperties(SourceProductionContext spc, ImmutableArray<RuleInfo> rules)
        {
            foreach (var r in rules)
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine();
                sb.Append("namespace ").Append(r.Namespace).AppendLine(";");
                sb.AppendLine();
                sb.Append("partial class ").AppendLine(r.SimpleTypeName);
                sb.AppendLine("{");
                sb.Append("    public global::XamlLint.Core.RuleMetadata Metadata { get; } = new(");
                sb.Append("Id: ").Append(Quote(r.Id)).Append(", ");
                sb.Append("UpstreamId: ").Append(QuoteOrNull(r.UpstreamId)).Append(", ");
                sb.Append("Title: ").Append(Quote(r.Title)).Append(", ");
                sb.Append("DefaultSeverity: (global::XamlLint.Core.Severity)").Append(r.DefaultSeverity).Append(", ");
                sb.Append("Dialects: (global::XamlLint.Core.Dialect)").Append(r.Dialects).Append(", ");
                sb.Append("HelpUri: ").Append(Quote(r.HelpUri)).Append(", ");
                sb.Append("Deprecated: ").Append(r.Deprecated ? "true" : "false").Append(", ");
                sb.Append("ReplacedBy: ").Append(QuoteOrNull(r.ReplacedBy));
                sb.AppendLine(");");
                sb.AppendLine("}");

                spc.AddSource($"{r.Namespace}.{r.SimpleTypeName}.Metadata.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }

        private static void EmitCatalog(SourceProductionContext spc, ImmutableArray<RuleInfo> rules)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();
            sb.AppendLine("namespace XamlLint.Core;");
            sb.AppendLine();
            sb.AppendLine("public static class GeneratedRuleCatalog");
            sb.AppendLine("{");
            sb.AppendLine("    public static IReadOnlyList<IXamlRule> Rules { get; } = new IXamlRule[]");
            sb.AppendLine("    {");
            foreach (var r in rules.OrderBy(x => x.Id, System.StringComparer.Ordinal))
            {
                sb.Append("        new ").Append(r.FullyQualifiedTypeName).AppendLine("(),");
            }
            sb.AppendLine("    };");
            sb.AppendLine("}");

            spc.AddSource("GeneratedRuleCatalog.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string Quote(string s) => "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        private static string QuoteOrNull(string? s) => s is null ? "null" : Quote(s);

        private sealed record RuleInfo(
            string FullyQualifiedTypeName,
            string SimpleTypeName,
            string Namespace,
            string Id,
            string? UpstreamId,
            string Title,
            int DefaultSeverity,
            int Dialects,
            string HelpUri,
            bool Deprecated,
            string? ReplacedBy);
    }
}
